apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db-deploy
    version: v1
  name: mysql-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db-deploy
      version: v1
  template:
    metadata:
      labels:
        app: mysql-db-deploy
        version: v1
    spec:
      containers:
      - name: mysql-db-deploy
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj19/mysql:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: rootpassword
        args: ["--authentication_policy","mysql_native_password"]
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: cluster-volume
      volumes:
      - name: cluster-volume
        persistentVolumeClaim:
          claimName: mysql-db-pvc
      securityContext:
        runAsUser: 1000
        