apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql_db-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi