apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
  labels:
    type: local
    app: mysql-db-deploy
spec:
  storageClassName: mysql-db-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/"