apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: mainpage-deploy
  name: mainpage-rt
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: mainpage-svc
    weight: 100