apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opinions_deploy
  name: opinions_deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opinions_deploy
  template:
    metadata:
      labels:
        app: opinions_deploy
    spec:
      containers:
      - image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj19/ opinions:1.0
        name: opinions_deploy
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: mysql_db_secret
        resources: {}
        volumeMounts:
        - name: config-map
          mountPath: /etc/myconfig/
      volumes:
      - name: config-map
        configMap:
          name: mysql_cm
status: {}
